FROM node:16

WORKDIR '/app'

COPY ["package.json", "package-lock.json*", "tsconfig.json", "./"]

RUN wget -O /bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
RUN chmod +x /bin/wait-for-it.sh

RUN npm ci && npm cache clean --force

COPY src ./src

CMD ["npm", "run", "dev"]